name: Build and Deploy Lambda Authorizer
on:
  push:
    paths:
      - 'authorizer/**'
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  build_and_deploy_authorizer:
    name: Build and Deploy Lambda Authorizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
      
      - name: Install and build
        run: |
          cd authorizer
          npm install
          npm run build --if-present

      - name: Zip
        run: |
          cd authorizer
          zip -r ../authorizer.zip ./*
      
      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.LAMBDA_AUTHORIZER_NAME }}
          zip_file: authorizer.zip
          environment: authorizationKey=${{ secrets.LAMBDA_AUTHORIZER_KEY }}